language:
    rust
rust:
  - stable
  - beta
  - nightly
before_script:
  rustup component add clippy-preview
script:
  - cargo build
  - cargo test
matrix:
  allow_failures:
    rust:
      nightly
  fast_finish:
    true
